own_id = 1

[participants]
nominal = 3
minimum = 2
probation_cycles = 10

[timing]
cycle_duration_ms  = 2000
# Phase timeouts.
init_sync_timeout_ms = 10000
peer_sync_timeout_ms = 500
cycle_sync_timeout_ms = 50
share_inputs_timeout_ms = 50
share_result_timeout_ms = 50
send_ack_timeout_ms = 50
error_management_timeout_ms = 50
system_state_crc_timeout_ms = 50
system_state_sync_timeout_ms = 50
resync_lost_peer_returning_timeout_ms = 30000
resync_lost_peer_healthy_timeout_ms = 5000
# Send intervals inside collect_phase loops.
init_sync_send_interval_ms = 10
peer_sync_request_interval_ms = 1
cycle_sync_send_interval_ms = 1
share_inputs_send_interval_ms = 1
share_result_send_interval_ms = 1
send_ack_send_interval_ms = 1
error_management_send_interval_ms = 1
system_state_crc_send_interval_ms = 1
system_state_sync_send_interval_ms = 5
resync_send_interval_ms = 10
# Misc.
stale_frame_threshold_ms = 50
resync_interval_cycles = 30

[transport]
interface = "lo"
multicast_group = "239.10.0.1"
port = 5555

[diagnostic]
enabled = true
interface = "lo"
multicast_group = "239.10.0.2"
port = 6666